apiVersion: v1
kind: Service
metadata:
  labels:
    app: labeltest-demo-service-1
    demo: demo-webhook
  name: labeltest-demo-service-1
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: demo-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
